import type { PlayerInfo } from './types';

export const PLAYER_INFO: Record<string, PlayerInfo> = {
  'Zhao Xintong': { country: '🇨🇳', seed: 1, status: 'Defending Champion', flag: 'CHN' },
  'Judd Trump': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: 2, status: 'World No. 1', flag: 'ENG' },
  'Kyren Wilson': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: 3, status: '2024 Champion', flag: 'ENG' },
  'Neil Robertson': { country: '🇦🇺', seed: 4, status: 'Former Champion', flag: 'AUS' },
  'John Higgins': { country: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', seed: 5, status: '4× World Champion', flag: 'SCO' },
  'Mark Williams': { country: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', seed: 6, status: '3× World Champion', flag: 'WAL' },
  'Mark Selby': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: 7, status: '4× World Champion', flag: 'ENG' },
  'Shaun Murphy': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: 8, status: '2005 Champion', flag: 'ENG' },
  'Xiao Guodong': { country: '🇨🇳', seed: 9, status: 'Top 16', flag: 'CHN' },
  'Wu Yize': { country: '🇨🇳', seed: 10, status: 'Top 16', flag: 'CHN' },
  'Barry Hawkins': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: 11, status: '2013 Finalist', flag: 'ENG' },
  "Ronnie O'Sullivan": { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: 12, status: '7× World Champion', flag: 'ENG' },
  'Chris Wakelin': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: 13, status: 'Top 16', flag: 'ENG' },
  'Mark Allen': { country: '🇮🇪', seed: 14, status: 'Top 16', flag: 'NIR' },
  'Si Jiahui': { country: '🇨🇳', seed: 15, status: '2023 Semi-Finalist', flag: 'CHN' },
  'Ding Junhui': { country: '🇨🇳', seed: 16, status: '2016 Finalist', flag: 'CHN' },
  'Liam Highfield': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: null, status: 'Qualifier', flag: 'ENG' },
  'Gary Wilson': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: null, status: 'Qualifier', flag: 'ENG' },
  'Stan Moody': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: null, status: 'Qualifier (Crucible Debutant)', flag: 'ENG' },
  'Pang Junxu': { country: '🇨🇳', seed: null, status: 'Qualifier', flag: 'CHN' },
  'Ali Carter': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: null, status: 'Qualifier (2× Finalist)', flag: 'ENG' },
  'Antoni Kowalski': { country: '🇵🇱', seed: null, status: 'Qualifier (1st Polish at Crucible)', flag: 'POL' },
  'Jak Jones': { country: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', seed: null, status: 'Qualifier (2024 Finalist)', flag: 'WAL' },
  'Fan Zhengyi': { country: '🇨🇳', seed: null, status: 'Qualifier', flag: 'CHN' },
  'Zhou Yuelong': { country: '🇨🇳', seed: null, status: 'Qualifier', flag: 'CHN' },
  'Lei Peifan': { country: '🇨🇳', seed: null, status: 'Qualifier', flag: 'CHN' },
  'Matthew Stevens': { country: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', seed: null, status: 'Qualifier', flag: 'WAL' },
  'He Guoqiang': { country: '🇨🇳', seed: null, status: 'Qualifier (Crucible Debutant)', flag: 'CHN' },
  'Liam Pullen': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: null, status: 'Qualifier (Crucible Debutant)', flag: 'ENG' },
  'Zhang Anda': { country: '🇨🇳', seed: null, status: 'Qualifier', flag: 'CHN' },
  'Hossein Vafaei': { country: '🇮🇷', seed: null, status: 'Qualifier', flag: 'IRN' },
  'David Gilbert': { country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', seed: null, status: 'Qualifier', flag: 'ENG' },
};
