import type { Team } from './types';

// Team picks per round.
// INVARIANT: For r1/r2/qf/sf, the i-th pick must correspond to the i-th match
// in the matching ROUND*_MATCHES array. Do not re-order without re-ordering both.

export const TEAMS: Team[] = [
  {
    name: 'Invincibles',
    color: '#0F5132',
    accent: '#10B981',
    icon: '⚡',
    motto: 'Unstoppable & Unbeatable',
    r1: ['Zhao Xintong','Judd Trump','Kyren Wilson','Neil Robertson','John Higgins','Mark Williams','Mark Selby','Shaun Murphy','Xiao Guodong','Wu Yize','Barry Hawkins',"Ronnie O'Sullivan",'Chris Wakelin','Mark Allen','Hossein Vafaei','Ding Junhui'],
    r2: ['Zhao Xintong','Xiao Guodong','Kyren Wilson','Mark Williams',"Ronnie O'Sullivan",'Mark Selby','Judd Trump','Neil Robertson'],
    qf: ['Zhao Xintong','Mark Allen','John Higgins','Wu Yize'],
    sf: ['Shaun Murphy','Wu Yize'],
    final: 'Wu Yize',
  },
  {
    name: 'Uncredibles',
    color: '#7C2D12',
    accent: '#EA580C',
    icon: '🔥',
    motto: 'Beyond Belief',
    r1: ['Zhao Xintong','Judd Trump','Stan Moody','Neil Robertson','Ali Carter','Mark Williams','Mark Selby','Shaun Murphy','Xiao Guodong','Wu Yize','Barry Hawkins',"Ronnie O'Sullivan",'Chris Wakelin','Mark Allen','Hossein Vafaei','Ding Junhui'],
    r2: ['Zhao Xintong','Shaun Murphy','Mark Allen','Mark Williams',"Ronnie O'Sullivan",'Mark Selby','Judd Trump','Neil Robertson'],
    qf: ['Zhao Xintong','Mark Allen','John Higgins','Hossein Vafaei'],
    sf: ['Shaun Murphy','Wu Yize'],
    final: 'Shaun Murphy',
  },
  {
    name: 'Hopeless',
    color: '#581C87',
    accent: '#A855F7',
    icon: '🎯',
    motto: 'Against All Odds',
    r1: ['Zhao Xintong','Judd Trump','Kyren Wilson','Neil Robertson','Ali Carter','Mark Williams','Mark Selby','Fan Zhengyi','Zhou Yuelong','Wu Yize','Barry Hawkins',"Ronnie O'Sullivan",'Chris Wakelin','Mark Allen','Si Jiahui','Ding Junhui'],
    r2: ['Zhao Xintong','Xiao Guodong','Mark Allen','Barry Hawkins','John Higgins','Mark Selby','Judd Trump','Neil Robertson'],
    qf: ['Zhao Xintong','Mark Allen','John Higgins','Wu Yize'],
    sf: ['Shaun Murphy','Wu Yize'],
    final: 'Wu Yize',
  },
  {
    name: 'Clueless',
    color: '#0E7490',
    accent: '#06B6D4',
    icon: '🎱',
    motto: 'Wild Guesses Win',
    r1: ['Zhao Xintong','Judd Trump','Kyren Wilson','Neil Robertson','John Higgins','Mark Williams','Mark Selby','Shaun Murphy','Xiao Guodong','Wu Yize','Barry Hawkins',"Ronnie O'Sullivan",'Liam Pullen','Mark Allen','Si Jiahui','David Gilbert'],
    r2: ['Zhao Xintong','Shaun Murphy','Kyren Wilson','Mark Williams','John Higgins','Mark Selby','Judd Trump','Chris Wakelin'],
    qf: ['Shaun Murphy','Barry Hawkins','John Higgins','Hossein Vafaei'],
    sf: ['Shaun Murphy','Mark Allen'],
    final: 'Shaun Murphy',
  },
  {
    name: 'Break Builders United',
    color: '#9F1239',
    accent: '#F43F5E',
    icon: '🏗️',
    motto: 'Building To Glory',
    r1: ['Zhao Xintong','Judd Trump','Kyren Wilson','Neil Robertson','John Higgins','Mark Williams','Mark Selby','Shaun Murphy','Xiao Guodong','Wu Yize','Barry Hawkins',"Ronnie O'Sullivan",'Chris Wakelin','Zhang Anda','Si Jiahui','David Gilbert'],
    r2: ['Zhao Xintong','Xiao Guodong','Mark Allen','Mark Williams',"Ronnie O'Sullivan",'Mark Selby','Judd Trump','Neil Robertson'],
    qf: ['Zhao Xintong','Mark Allen','John Higgins','Wu Yize'],
    sf: ['Shaun Murphy','Wu Yize'],
    final: 'Wu Yize',
  },
  {
    name: 'The Untouchables',
    color: '#1E3A8A',
    accent: '#3B82F6',
    icon: '🛡️',
    motto: 'Untainted by Failure',
    r1: ['Zhao Xintong','Gary Wilson','Stan Moody','Pang Junxu','John Higgins','Mark Williams','Mark Selby','Fan Zhengyi','Xiao Guodong','Wu Yize','Barry Hawkins',"Ronnie O'Sullivan",'Chris Wakelin','Zhang Anda','Hossein Vafaei','Ding Junhui'],
    r2: ['Zhao Xintong','Shaun Murphy','Mark Allen','Mark Williams',"Ronnie O'Sullivan",'Mark Selby','Judd Trump','Neil Robertson'],
    qf: ['Zhao Xintong','Mark Allen','John Higgins','Wu Yize'],
    sf: ['Shaun Murphy','Wu Yize'],
    final: 'Wu Yize',
  },
  {
    name: 'Selbies',
    color: '#92400E',
    accent: '#F59E0B',
    icon: '👑',
    motto: 'Slow & Steady',
    r1: ['Zhao Xintong','Judd Trump','Kyren Wilson','Neil Robertson','Ali Carter','Mark Williams','Mark Selby','Shaun Murphy','Zhou Yuelong','Wu Yize','Barry Hawkins',"Ronnie O'Sullivan",'Chris Wakelin','Mark Allen','Si Jiahui','David Gilbert'],
    r2: ['Zhao Xintong','Shaun Murphy','Mark Allen','Mark Williams',"Ronnie O'Sullivan",'Mark Selby','Judd Trump','Chris Wakelin'],
    qf: ['Zhao Xintong','Barry Hawkins','John Higgins','Wu Yize'],
    sf: ['Shaun Murphy','Mark Allen'],
    final: 'Wu Yize',
  },
  {
    name: 'One Four Sevens',
    color: '#365314',
    accent: '#84CC16',
    icon: '💫',
    motto: 'Maximum Effort',
    r1: ['Zhao Xintong','Gary Wilson','Stan Moody','Neil Robertson','John Higgins','Mark Williams','Jak Jones','Shaun Murphy','Zhou Yuelong','Wu Yize','Barry Hawkins',"Ronnie O'Sullivan",'Chris Wakelin','Zhang Anda','Hossein Vafaei','David Gilbert'],
    r2: ['Zhao Xintong','Shaun Murphy','Mark Allen','Mark Williams',"Ronnie O'Sullivan",'Wu Yize','Judd Trump','Chris Wakelin'],
    qf: ['Zhao Xintong','Barry Hawkins','Neil Robertson','Wu Yize'],
    sf: ['Shaun Murphy','Wu Yize'],
    final: 'Wu Yize',
  },
];
